fastd2/bmxd: update docs url

diff --git a/salt/freifunk/base/fastd/etc/init.d/S53backbone-fastd2 b/salt/freifunk/base/fastd/etc/init.d/S53backbone-fastd2
--- a/salt/freifunk/base/fastd/etc/init.d/S53backbone-fastd2
+++ b/salt/freifunk/base/fastd/etc/init.d/S53backbone-fastd2
@@ -11,6 +11,9 @@
 # Description:       start fastd backbone
 ### END INIT INFO
 
+# sources: https://projects.universe-factory.net/projects/fastd/wiki
+# docs: https://fastd.readthedocs.org/en/v18/
+
 DAEMON='/usr/local/bin/fastd'
 CONF_DIR='/etc/fastd'
 FASTD_CONF="$CONF_DIR"/fastd2.conf
@@ -27,22 +30,18 @@ fi
 
 generate_fastd_conf()
 {
- # sources: https://projects.universe-factory.net/projects/fastd/wiki
- # docs: http://fastd.readthedocs.org/en/v17/
+	MTU=1200
+	secret="$(nvram get fastd_secret)"
+	if [ -z "$secret" ]; then
+		logger -t fastd "no secret key - abort"
+		exit 1
+ 	fi
 
- MTU=1200
- secret="$(nvram get fastd_secret)"
- if [ -z "$secret" ]; then
-	logger -t fastd "no secret key - abort"
-	exit 1
- fi
-
- cat << EOM > "$FASTD_CONF"
+	cat << EOM > "$FASTD_CONF"
 log level warn;
 log to syslog level debug;
 mode tap;
 interface "tbb_fastd2";
-#prefer "null"
 method "null";
 method "null+salsa2012+umac";
 method "salsa2012+umac";
