fastd: fix generate_keys

diff --git a/salt/freifunk/base/fastd/etc/init.d/S53backbone-fastd2 b/salt/freifunk/base/fastd/etc/init.d/S53backbone-fastd2
--- a/salt/freifunk/base/fastd/etc/init.d/S53backbone-fastd2
+++ b/salt/freifunk/base/fastd/etc/init.d/S53backbone-fastd2
@@ -32,7 +32,8 @@ fi
 
 generate_keys()
 {
-	if [ -z "$(uci -q get ffdd.fastd.secret)" -o -z "$(uci -q get ffdd.fastd.public)" ]; then
+	if [ -z "$(uci -q get ffdd.fastd.secret)" ] || [ -z "$(uci -q get ffdd.fastd.public)" ] &&
+	[ "$(uci -q get ffdd.fastd.secret)" = '-' ] || [ "$(uci -q get ffdd.fastd.public)" = '-' ]; then
 		# generate fastd secret & public key
 		fastd --generate-key > /tmp/.ffdd_h.txt
 
@@ -139,11 +140,11 @@ case "$1" in
 	printf 'Starting backbone...\n'
 
 	# generate keys if not present
-	
+
 	generate_keys
 
 	# overwrite values if we have "old" config
-	if [ -n "$(uci -q get ffdd.sys.fastd_secret)" -a -n "$(uci -q get ffdd.sys.fastd_public)" ]; then
+	if [ -n "$(uci -q get ffdd.sys.fastd_secret)" ] && [ -n "$(uci -q get ffdd.sys.fastd_public)" ]; then
 		uci set ffdd.fastd.restrict="$(uci -qX get ffdd.sys.fastd_restrict)"
 		uci delete ffdd.sys.fastd_restrict
 		uci set ffdd.fastd.secret="$(uci -qX get ffdd.sys.fastd_secret)"
@@ -185,7 +186,7 @@ case "$1" in
 		$DAEMON --generate-key
 		exit 0
 	else
-		printf "$DAEMON not found\n" 1>&2
+		printf '%s not found\n' "$DAEMON" 1>&2
 		exit 1
 	fi
   ;;
